package com.teleops.teleops_ai.ticket.model;

import java.time.LocalDateTime;

/**
 * Incident Report - Embedded MongoDB Document
 *
 * This is NOT a top-level collection.
 * It is embedded inside the Ticket document.
 *
 * Populated by the AI module in Phase 10 when a manager
 * requests an incident report for a closed ticket.
 *
 * MongoDB document structure:
 * {
 *   "_id": "...",
 *   "ticketNumber": "TKT-2024-00001",
 *   ...,
 *   "incidentReport": {
 *     "summary": "...",
 *     "timeline": "...",
 *     "rootCause": "...",
 *     "resolution": "...",
 *     "recommendations": "...",
 *     "generatedAt": "2024-01-15T10:30:00"
 *   }
 * }
 *
 * All fields are null until AI generates the report.
 * Phase 10 calls AiService which populates this object
 * and saves it back to the ticket.
 */
public class IncidentReport {

    /**
     * Executive summary of the incident.
     * 2-3 sentences suitable for management.
     */
    private String summary;

    /**
     * Chronological timeline of events.
     * From alarm raised to ticket closed.
     */
    private String timeline;

    /**
     * Root cause identified during investigation.
     */
    private String rootCause;

    /**
     * What was done to resolve the issue.
     */
    private String resolution;

    /**
     * AI recommendations to prevent recurrence.
     */
    private String recommendations;

    /**
     * When this report was generated by AI.
     */
    private LocalDateTime generatedAt;

    // ─────────────────────────────────────────
    // Constructors
    // ─────────────────────────────────────────

    public IncidentReport() {
    }

    public IncidentReport(String summary, String timeline,
                          String rootCause, String resolution,
                          String recommendations) {
        this.summary = summary;
        this.timeline = timeline;
        this.rootCause = rootCause;
        this.resolution = resolution;
        this.recommendations = recommendations;
        this.generatedAt = LocalDateTime.now();
    }

    // ─────────────────────────────────────────
    // Getters and Setters
    // ─────────────────────────────────────────

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getTimeline() {
        return timeline;
    }

    public void setTimeline(String timeline) {
        this.timeline = timeline;
    }

    public String getRootCause() {
        return rootCause;
    }

    public void setRootCause(String rootCause) {
        this.rootCause = rootCause;
    }

    public String getResolution() {
        return resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    public String getRecommendations() {
        return recommendations;
    }

    public void setRecommendations(String recommendations) {
        this.recommendations = recommendations;
    }

    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
    }
}